In [14]:
import pandas as pd
import numpy as np
import matplotlib as mlt
import csv

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

import warnings
warnings.filterwarnings('ignore')

In [15]:
df_recipes = pd.read_csv('C:/Users/wellb/Downloads/datasets/daily_food_nutrition_dataset.csv')

In [16]:
df_recipes.columns

Index(['Date', 'User_ID', 'Food_Item', 'Category', 'Calories (kcal)',
       'Protein (g)', 'Carbohydrates (g)', 'Fat (g)', 'Fiber (g)',
       'Sugars (g)', 'Sodium (mg)', 'Cholesterol (mg)', 'Meal_Type',
       'Water_Intake (ml)'],
      dtype='object')

In [17]:
df_recipes.head(10)

,Date,User_ID,Food_Item,Category,Calories (kcal),Protein (g),Carbohydrates (g),Fat (g),Fiber (g),Sugars (g),Sodium (mg),Cholesterol (mg),Meal_Type,Water_Intake (ml)
0,2024-09-11,496,Eggs,Meat,173,42.4,83.7,1.5,1.5,12.7,752,125,Lunch,478
1,2024-12-17,201,Apple,Fruits,66,39.2,13.8,3.2,2.6,12.2,680,97,Lunch,466
2,2024-06-09,776,Chicken Breast,Meat,226,27.1,79.1,25.8,3.2,44.7,295,157,Breakfast,635
3,2024-08-27,112,Banana,Fruits,116,43.4,47.1,16.1,6.5,44.1,307,13,Snack,379
4,2024-07-28,622,Banana,Fruits,500,33.9,75.8,47.0,7.8,19.4,358,148,Lunch,471
5,2024-01-19,620,Oats,Grains,387,31.2,6.8,39.5,5.1,0.7,300,244,Dinner,727
6,2024-07-27,714,Carrot,Vegetables,138,28.2,12.4,20.2,2.8,37.8,933,15,Dinner,733
7,2024-10-21,992,Cookies,Snacks,69,36.8,17.8,15.0,9.6,36.4,185,228,Snack,386
8,2024-07-23,535,Apple,Fruits,568,6.7,7.0,23.4,6.4,46.9,336,129,Breakfast,931
9,2024-09-08,594,Quinoa,Grains,204,19.3,62.7,31.8,6.8,40.3,887,135,Snack,662

In [18]:
print(df_recipes.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               10000 non-null  object
 1   User_ID            10000 non-null  int64
 2   Food_Item          10000 non-null  object
 3   Category           10000 non-null  object
 4   Calories (kcal)    10000 non-null  int64
 5   Protein (g)        10000 non-null  float64
 6   Carbohydrates (g)  10000 non-null  float64
 7   Fat (g)            10000 non-null  float64
 8   Fiber (g)          10000 non-null  float64
 9   Sugars (g)         10000 non-null  float64
 10  Sodium (mg)        10000 non-null  int64
 11  Cholesterol (mg)   10000 non-null  int64
 12  Meal_Type          10000 non-null  object
 13  Water_Intake (ml)  10000 non-null  int64
dtypes: float64(5), int64(5), object(4)
memory usage: 1.1+ MB
None

In [19]:
df_category = df_recipes.groupby('Category').sum().reset_index

In [20]:
top_nutrition_density_foods = df_category
plt.figure(figsize=(12, 8))
sns.barplot(x='Nutrition Density', y='food', data=top_nutrition_density_foods, palette='viridis')
plt.title('Top 10 Food Items by Nutrition Density')
plt.show()

TypeError: Data source must be a DataFrame or Mapping, not <class 'method'>.

In [6]:
df_vegan = pd.read_csv('C:/Users/user/Downloads/Datasets-D/vegan.csv')

In [7]:
print(df_vegan.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1522 entries, 0 to 1521
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Diet_type        1522 non-null   object
 1   Recipe_name      1522 non-null   object
 2   Cuisine_type     1522 non-null   object
 3   Protein(g)       1522 non-null   float64
 4   Carbs(g)         1522 non-null   float64
 5   Fat(g)           1522 non-null   float64
 6   Extraction_day   1522 non-null   object
 7   Extraction_time  1522 non-null   object
dtypes: float64(3), object(5)
memory usage: 95.3+ KB
None

In [8]:
df_vegan.head(10)

,Diet_type,Recipe_name,Cuisine_type,Protein(g),Carbs(g),Fat(g),Extraction_day,Extraction_time
0,vegan,Spiked Vegan Eggnog,american,46.36,84.52,42.61,2022-10-16,20:02:29
1,vegan,Vegan Cucumber Tea Sandwiches,american,41.73,143.91,73.88,2022-10-16,20:02:29
2,vegan,Vegan Broccoli Soup Recipe,american,103.83,82.54,139.30,2022-10-16,20:02:29
3,vegan,Baked Vegan Mac and Cheese Recipe,american,140.19,524.38,221.29,2022-10-16,20:02:29
4,vegan,Vegan Nachos,american,73.05,266.38,166.64,2022-10-16,20:02:29
5,vegan,The Best Vegan Breakfast Sandwich,american,143.13,208.42,189.86,2022-10-16,20:02:29
6,vegan,{Vegan} Peanut Butter & Honey Muffins recipes,american,29.53,168.46,59.83,2022-10-16,20:02:29
7,vegan,Vegan Pots de Crème,american,45.25,106.45,98.01,2022-10-16,20:02:29
8,vegan,Vegan tiffin,american,60.38,272.18,287.22,2022-10-16,20:02:29
9,vegan,Vegan Stovetop Lasagna,american,124.77,512.21,147.15,2022-10-16,20:02:29

In [9]:
df_meal_plans = pd.read_csv('C:/Users/user/Downloads/Datasets-D/healthy_meal_plans.csv')

In [10]:
print(df_meal_plans.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   meal_name        500 non-null    object
 1   num_ingredients  500 non-null    float64
 2   calories         500 non-null    float64
 3   prep_time        500 non-null    float64
 4   protein          500 non-null    float64
 5   fat              500 non-null    float64
 6   carbs            500 non-null    float64
 7   vegan            500 non-null    int64
 8   vegetarian       500 non-null    int64
 9   keto             500 non-null    int64
 10  paleo            500 non-null    int64
 11  gluten_free      500 non-null    int64
 12  mediterranean    500 non-null    int64
 13  is_healthy       500 non-null    int64
dtypes: float64(6), int64(7), object(1)
memory usage: 54.8+ KB
None

In [11]:
df_meal_plans.head(10)

,meal_name,num_ingredients,calories,prep_time,protein,fat,carbs,vegan,vegetarian,keto,paleo,gluten_free,mediterranean,is_healthy
0,Gluten-Free Pasta,0.272727,0.490909,0.84,0.783679,0.597907,0.444572,0,0,0,0,1,0,1
1,Grilled Salmon,0.909091,0.158182,0.70,0.143588,0.652082,0.050609,0,0,1,1,1,1,0
2,Lentil Soup,0.454545,0.700000,0.40,0.620637,0.612748,0.000688,0,1,0,0,0,0,0
3,Chickpea Stew,0.909091,0.105455,0.82,0.046893,0.975761,0.229026,1,1,0,0,0,0,0
4,Turkey Lettuce Wraps,0.181818,0.441818,0.04,0.864340,0.681575,0.449293,0,0,1,1,1,1,0
5,Cauliflower Rice Bowl,0.272727,0.572727,0.26,0.812533,0.304936,0.092351,1,1,0,1,1,0,1
6,Almond Flour Pancakes,1.000000,0.665455,0.12,0.613114,0.834846,0.168926,0,1,1,1,1,0,0
7,Chickpea Stew,0.272727,0.703636,0.02,0.427325,0.208021,0.567861,1,1,0,0,0,0,1
8,Cauliflower Rice Bowl,0.818182,0.292727,0.18,0.899406,0.598960,0.926165,1,1,0,1,1,0,0
9,Vegan Curry,0.545455,0.456364,0.78,0.848855,0.748756,0.539526,1,1,0,0,0,0,0

In [3]:
# Import transfore
# pip install transformers

In [1]:
import transformers
# import Pytorch
import tensorflow as tf 
import pandas as pd
import json
import pandas as pd
import numpy as np
import matplotlib as mlt
import csv

In [2]:
# from transformers import AutoTokenizer, AutoModelForCausaLLM
from transformers import AutoTokenizer, AutoModelForCausalLM

In [3]:
df_recipes_NGL = pd.read_csv('C:/Users/user/Downloads/Datasets-D/RecipeNLG_dataset.csv')
df_recipes_NGL.head(5)

,Unnamed: 0,title,ingredients,directions,link,source,NER
0,0,No-Bake Nut Cookies,"[""1 c. firmly packed brown sugar"", ""1/2 c. eva...","[""In a heavy 2-quart saucepan, mix brown sugar...",www.cookbooks.com/Recipe-Details.aspx?id=44874,Gathered,"[""brown sugar"", ""milk"", ""vanilla"", ""nuts"", ""bu..."
1,1,Jewell Ball'S Chicken,"[""1 small jar chipped beef, cut up"", ""4 boned ...","[""Place chipped beef on bottom of baking dish....",www.cookbooks.com/Recipe-Details.aspx?id=699419,Gathered,"[""beef"", ""chicken breasts"", ""cream of mushroom..."
2,2,Creamy Corn,"[""2 (16 oz.) pkg. frozen corn"", ""1 (8 oz.) pkg...","[""In a slow cooker, combine all ingredients. C...",www.cookbooks.com/Recipe-Details.aspx?id=10570,Gathered,"[""frozen corn"", ""cream cheese"", ""butter"", ""gar..."
3,3,Chicken Funny,"[""1 large whole chicken"", ""2 (10 1/2 oz.) cans...","[""Boil and debone chicken."", ""Put bite size pi...",www.cookbooks.com/Recipe-Details.aspx?id=897570,Gathered,"[""chicken"", ""chicken gravy"", ""cream of mushroo..."
4,4,Reeses Cups(Candy),"[""1 c. peanut butter"", ""3/4 c. graham cracker ...","[""Combine first four ingredients and press in ...",www.cookbooks.com/Recipe-Details.aspx?id=659239,Gathered,"[""peanut butter"", ""graham cracker crumbs"", ""bu..."

In [6]:
recipe = df_recipes_NGL['ingredients'][0]
print(type(recipe)

<class 'str'>

In [4]:
# food dataset
df_food = pd.read_csv('C:/Users/user/Downloads/Datasets-D/daily_food_nutrition_dataset.csv')
df_food.head(5)

,Date,User_ID,Food_Item,Category,Calories (kcal),Protein (g),Carbohydrates (g),Fat (g),Fiber (g),Sugars (g),Sodium (mg),Cholesterol (mg),Meal_Type,Water_Intake (ml)
0,2024-09-11,496,Eggs,Meat,173,42.4,83.7,1.5,1.5,12.7,752,125,Lunch,478
1,2024-12-17,201,Apple,Fruits,66,39.2,13.8,3.2,2.6,12.2,680,97,Lunch,466
2,2024-06-09,776,Chicken Breast,Meat,226,27.1,79.1,25.8,3.2,44.7,295,157,Breakfast,635
3,2024-08-27,112,Banana,Fruits,116,43.4,47.1,16.1,6.5,44.1,307,13,Snack,379
4,2024-07-28,622,Banana,Fruits,500,33.9,75.8,47.0,7.8,19.4,358,148,Lunch,471

In [5]:
df_food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               10000 non-null  object
 1   User_ID            10000 non-null  int64
 2   Food_Item          10000 non-null  object
 3   Category           10000 non-null  object
 4   Calories (kcal)    10000 non-null  int64
 5   Protein (g)        10000 non-null  float64
 6   Carbohydrates (g)  10000 non-null  float64
 7   Fat (g)            10000 non-null  float64
 8   Fiber (g)          10000 non-null  float64
 9   Sugars (g)         10000 non-null  float64
 10  Sodium (mg)        10000 non-null  int64
 11  Cholesterol (mg)   10000 non-null  int64
 12  Meal_Type          10000 non-null  object
 13  Water_Intake (ml)  10000 non-null  int64
dtypes: float64(5), int64(5), object(4)
memory usage: 1.1+ MB

In [16]:
print(df_food['Meal_type' == 'Lunch'])

KeyError: False

In [4]:
model_id = "distilgpt2"
device = "mps"

In [5]:
model = AutoModelForCausalLM.from_pretrained(model_id)
tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token

model

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-5): 6 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

In [6]:
print(df_recipes_NGL.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2231142 entries, 0 to 2231141
Data columns (total 7 columns):
 #   Column       Dtype
---  ------       -----
 0   Unnamed: 0   int64
 1   title        object
 2   ingredients  object
 3   directions   object
 4   link         object
 5   source       object
 6   NER          object
dtypes: int64(1), object(6)
memory usage: 119.2+ MB
None

In [7]:
df_recipes_NGL.head(5)

,Unnamed: 0,title,ingredients,directions,link,source,NER
0,0,No-Bake Nut Cookies,"[""1 c. firmly packed brown sugar"", ""1/2 c. eva...","[""In a heavy 2-quart saucepan, mix brown sugar...",www.cookbooks.com/Recipe-Details.aspx?id=44874,Gathered,"[""brown sugar"", ""milk"", ""vanilla"", ""nuts"", ""bu..."
1,1,Jewell Ball'S Chicken,"[""1 small jar chipped beef, cut up"", ""4 boned ...","[""Place chipped beef on bottom of baking dish....",www.cookbooks.com/Recipe-Details.aspx?id=699419,Gathered,"[""beef"", ""chicken breasts"", ""cream of mushroom..."
2,2,Creamy Corn,"[""2 (16 oz.) pkg. frozen corn"", ""1 (8 oz.) pkg...","[""In a slow cooker, combine all ingredients. C...",www.cookbooks.com/Recipe-Details.aspx?id=10570,Gathered,"[""frozen corn"", ""cream cheese"", ""butter"", ""gar..."
3,3,Chicken Funny,"[""1 large whole chicken"", ""2 (10 1/2 oz.) cans...","[""Boil and debone chicken."", ""Put bite size pi...",www.cookbooks.com/Recipe-Details.aspx?id=897570,Gathered,"[""chicken"", ""chicken gravy"", ""cream of mushroo..."
4,4,Reeses Cups(Candy),"[""1 c. peanut butter"", ""3/4 c. graham cracker ...","[""Combine first four ingredients and press in ...",www.cookbooks.com/Recipe-Details.aspx?id=659239,Gathered,"[""peanut butter"", ""graham cracker crumbs"", ""bu..."

In [8]:
df_recipes_NGL.columns

Index(['Unnamed: 0', 'title', 'ingredients', 'directions', 'link', 'source',
       'NER'],
      dtype='object')

In [9]:
df_recipes_NGL[['title','directions']]

,title,directions
0,No-Bake Nut Cookies,"[""In a heavy 2-quart saucepan, mix brown sugar..."
1,Jewell Ball'S Chicken,"[""Place chipped beef on bottom of baking dish...."
2,Creamy Corn,"[""In a slow cooker, combine all ingredients. C..."
3,Chicken Funny,"[""Boil and debone chicken."", ""Put bite size pi..."
4,Reeses Cups(Candy),"[""Combine first four ingredients and press in ..."
...,...,...
2231137,Sunny's Fake Crepes,"[""Spread hazelnut spread on 1 side of each tor..."
2231138,Devil Eggs,"[""Boil eggs on medium for 30mins."", ""Then cool..."
2231139,Extremely Easy and Quick - Namul Daikon Salad,"[""Julienne the daikon and squeeze out the exce..."
2231140,Pan-Roasted Pork Chops With Apple Fritters,"[""In a large bowl, mix the apple cider with 4 ..."
2231141,Polpette in Spicy Tomato Sauce,"[""Preheat the oven to 350."", ""In a bowl, mix t..."

In [21]:
# Creating the fuction to add a new columns with two columns
def create_rec_string_col(data):

    dfe = df_recipes_NGL['directions'].to_json()
    dfe
    # necessary to convert the data series into json
    # rec_dir = " ".join(json.loads(data["directions"]))
    rec_dir = " ".join(dfe)
    return rec_dir
    # rec_tit = data['title']
    # rec_string = f"Title: {rec_tit} | Directions:  {rec_dir}"
    # data['rec_string'] = rec_string
    # return data

In [20]:
df = df_recipes_NGL.apply(create_rec_string_col, axis=1)
df = df.filter(['rec_string'])
df

KeyboardInterrupt

In [ ]:
dfe = df_recipes_NGL['directions'].to_json()
dfe

In [ ]:
from datasets import Dataset

def tokenize_batch(batch):
    return tokenizer(
        batch['rec_string'],
        truncation=True,
        max_length=64,
        return_overflowing_tokens=True
    )